"""empty message

Revision ID: dec523369fda
Revises: e3c7edeb57ac
Create Date: 2020-05-25 16:39:05.999551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec523369fda'
down_revision = 'e3c7edeb57ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
